version: "3.9"

services:
  ml-app:
    image: omarmoura/desafio-ml-project:latest
    container_name: ml-app
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./app:/app/app:ro
      - ./src:/app/src
      - ./notebooks:/app/notebooks
    environment:
      - PYTHONPATH=/app
      - MODEL_PATH=/app/models
      - DATA_PATH=/app/data
      - LOG_LEVEL=INFO
    networks:
      - ml-network
    restart: unless-stopped
    command: ["uvicorn", "app.fast_main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "1"]

  streamlit-app:
    image: omarmoura/desafio-ml-project:latest
    container_name: streamlit-app
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./models:/app/models:ro
      - ./app:/app/app:ro
      - ./src:/app/src
      - ./notebooks:/app/notebooks
    environment:
      - PYTHONPATH=/app
      - MODEL_PATH=/app/models
      - DATA_PATH=/app/data
    networks:
      - ml-network
    restart: unless-stopped
    depends_on:
      - ml-app
    command: ["streamlit", "run", "app/streamlit_main.py", "--server.address", "0.0.0.0", "--server.port", "8501", "--server.headless", "true"]

networks:
  ml-network:
    driver: bridge